import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

import Button from "../components/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Encod</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/encod.svg" />
      </Head>

      <Button name="Create a room" />
    </div>
  );
}
